# Generated by Django 4.0.4 on 2022-05-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_image_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
