# Generated by Django 4.0.4 on 2022-05-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_pictures_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc',
            new_name='location',
        ),
    ]
