# Generated by Django 4.0.4 on 2022-06-02 09:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_loc_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
